# vi: ft=dockerfile
FROM porzione/citest

### java https://adoptopenjdk.net/installation.html#x64_linux-jdk

ARG JAVA_SUM=7b7884f2eb2ba2d47f4c0bf3bb1a2a95b73a3a7734bd47ebf9798483a7bcc423
ARG JAVA_URL=https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_x64_linux_hotspot_8u232b09.tar.gz 
RUN curl -L $JAVA_URL -o /tmp/OpenJDK8.tar.gz \
    && tar xzf /tmp/OpenJDK8.tar.gz -C /opt \
    && echo "$JAVA_SUM /tmp/OpenJDK8.tar.gz" | sha256sum -c - 
ENV PATH="/opt/jdk8u232-b09/bin:$PATH"

### CCM (Cassandra Cluster Manager)

ARG CASSANDRA_VER=3.11.5
RUN ccm create --version $CASSANDRA_VER --nodes 3 test

### PostgreSQL

ENV PG_VER=11
ARG PG_CONF=/etc/postgresql/${PG_VER}/main/postgresql.conf
ARG PG_HBA=/etc/postgresql/${PG_VER}/main/pg_hba.conf
ARG PG_TMP=/var/run/postgresql/${PG_VER}-main.pg_stat_tmp
ARG PG_DBUSER=test
ARG PG_DBPASS=test
ARG PG_DBNAME=test
ARG PG_MAXCONN=500 
ARG PG_PORT=5432

RUN apt-get update && apt-get -y --no-install-recommends install postgresql-${PG_VER}
RUN test -d ${PG_TMP} || sudo -u postgres mkdir ${PG_TMP} \
    && echo "listen_addresses = '*'" >> ${PG_CONF} \
    && echo "max_connections = ${PG_MAXCONN}" >> ${PG_CONF} \
    && echo "host ${PG_DBNAME} ${PG_DBUSER} 0.0.0.0/0 md5" >> ${PG_HBA} \
    && echo sed -i -E "s/#?port = [[:digit:]]+/port = ${PG_PORT}/" ${PG_CONF} \
    && sudo -u postgres pg_ctlcluster $PG_VER main start \
    && echo "Waiting PostgreSQL ${PG_VER} to launch on ${PG_PORT}..." \
    && while ! sudo -u postgres pg_isready -p ${PG_PORT}; do sleep 0.5; done \
    && echo "Creating user and database" \
    && echo "CREATE USER ${PG_DBUSER} PASSWORD '${PG_DBPASS}'" | sudo -u postgres psql \
    && echo "CREATE DATABASE ${PG_DBNAME} WITH OWNER=${PG_DBUSER}" | sudo -u postgres psql \
    && sudo -u postgres pg_ctlcluster $PG_VER main stop

### daemon

ADD daemon.sh /
CMD /daemon.sh

### cleanup

RUN rm /tmp/*.tar.gz \
    && rm -rf /usr/share/man \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

ARG SOURCE_BRANCH=""
ARG SOURCE_COMMIT=""
RUN echo $(date +'%y%m%d_%H%M%S_%Z') ${SOURCE_BRANCH} ${SOURCE_COMMIT} > /build.txt
